### ISSUE TITLE
Translations in workflow.sql

### ISSUE THREAD

**Issue by tamslo** [tamslo/KnowMin-MIK#1]
Review, which translations actually are necessary for suggestions and which ones could be moved to another script for evaluation.

**Comment by jpheuz** [comment]
:+1:

**Comment by mmkonrad** [comment]
do you mean from md5 to clear? In the end, only the suggestions need to get translated back to cleartext. The others are just for reviewing the interim results and for tracking issues and stuff for comprehension of the current outcome.
