### ISSUE TITLE
Organize branches

### ISSUE THREAD

**Issue by tamslo** [tamslo/KnowMin-MIK#2]
I would like to keep "hacky_stuff", "other_hacky_stuff" and "translating_php_to_python" and simply move them into a new branch "old_versions".

Additionally, work on "going_symmetric" is still in progress.

Please comment: Do we still need dev or can we just work on master? Are there other branches you would like to keep?

**Comment by jpheuz** [comment]
I don't think this has top priority, but if you feel better with a tidy repo then go for it :). It's a good idea to keep the old stuff, especially the python db connection and other helpers, as I might use them later.

**Comment by mmkonrad** [comment]
If the master is currently up to date, then let's go fot it.
